spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banshee?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: banshee
    password: banshee2020*.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true