spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banshee?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: banshee
    password: banshee2020*.